coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

ignore:
  - "components/ui/**/*"  # Ignoring UI components from coverage
  - "**/*.test.{js,jsx,ts,tsx}"
  - "**/*.spec.{js,jsx,ts,tsx}"
  - "**/tests/**"
  - "coverage/**"

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

test_analytics:
  enabled: true
  strict: false
  tests:
    - "**/*.test.{js,jsx,ts,tsx}"
  annotations:
    - type: "test_failures"
      level: "warning"
    - type: "test_performance"
      level: "notice"
