coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

ignore:
  - "components/ui/**/*"  # Ignoring UI components from coverage
  - "**/*.test.{js,jsx,ts,tsx}"
  - "**/*.spec.{js,jsx,ts,tsx}"
  - "**/tests/**"
  - "coverage/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
