name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage and analytics
      run: npm run test:ci

    - name: Upload coverage and test analytics to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: rahulchhabria/sentry-playground
        files: |
          ./coverage/lcov.info
          ./reports/jest-junit.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
