name: Pixee

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  pixee:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Pixee Action
      - uses: sentry-playground/pixee-action@v1
        with:
          fetch-depth: 0
      - name: Pixee
        uses: pixee/pixee-action@v1
        with:
          ruler: secure-code
          fail-on-findings: false
